name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  test-main:
    name: Nightly Testing (dev-main)
    uses: ./.github/workflows/_test.yaml
    with:
      php-version: 8.3
      typo3-version: dev-main
      stability: dev
      unit-coverage-name: coverage-unit-main
      functional-coverage-name: coverage-functional-main
      composer-remove: phpstan/phpstan saschaegerer/phpstan-typo3

  test-lts:
    name: Nightly Testing (current LTS)
    uses: ./.github/workflows/_test.yaml
    with:
      php-version: 8.3
      typo3-version: '^12'
      unit-coverage-name: coverage-unit-lts
      functional-coverage-name: coverage-functional-lts
